version: '3.8'

services:
  airbnb-clone:
    container_name: airbnb-clone
    image: airbnb-clone
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:  
      - .env
    environment:
      - NODE_ENV=production
    restart: always
