version: '3.8'

services:
  airbnb-clone:
    container_name: airbnb-clone
    image: airbnb-clone
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: always
