version: '3.8'

services:
  portfolio:
    container_name: airbnb-clone
    image: airbnb-clone
    build: .
    ports:
      - "3001:3001"
    volumes:
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=production
    restart: always
